global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-backend'
    static_configs:
      - targets: ['my_backend:5000']

  - job_name: 'nginx-frontend'
    static_configs:
      - targets: ['nginx_exporter:9113']
